# Generated by Django 3.2 on 2022-12-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='text',
            field=models.TextField(default=None, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
