# Generated by Django 3.2 on 2022-12-28 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diabetes_012', models.PositiveSmallIntegerField()),
                ('HighBP', models.PositiveSmallIntegerField()),
                ('HighChol', models.PositiveSmallIntegerField()),
                ('CholCheck', models.PositiveSmallIntegerField()),
                ('BMI', models.PositiveSmallIntegerField()),
                ('Smoker', models.PositiveSmallIntegerField()),
                ('Stroke', models.PositiveSmallIntegerField()),
                ('HeartDiseaseorAttack', models.PositiveSmallIntegerField()),
                ('PhysActivity', models.PositiveSmallIntegerField()),
                ('Fruits', models.PositiveSmallIntegerField()),
                ('Veggies', models.PositiveSmallIntegerField()),
                ('HvyAlcoholConsump', models.PositiveSmallIntegerField()),
                ('AnyHealthcare', models.PositiveSmallIntegerField()),
                ('NoDocbcCost', models.PositiveSmallIntegerField()),
                ('GenHlth', models.PositiveSmallIntegerField()),
                ('MentHlth', models.PositiveSmallIntegerField()),
                ('PhysHlth', models.PositiveSmallIntegerField()),
                ('DiffWalk', models.PositiveSmallIntegerField()),
                ('Sex', models.PositiveSmallIntegerField()),
                ('Age', models.PositiveSmallIntegerField()),
                ('Education', models.PositiveSmallIntegerField()),
                ('Label', models.CharField(max_length=32)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diabetes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
